# Generated by Django 5.2.6 on 2025-09-07 11:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seller",
                    models.CharField(
                        default="Open Mineral",
                        help_text="Seller company name",
                        max_length=255,
                    ),
                ),
                (
                    "buyer",
                    models.CharField(
                        default="Company A, John Materials",
                        help_text="Buyer company name",
                        max_length=255,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        help_text="Material type (e.g., Akzhal, Lead concentrate)",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity in specified unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
            ],
        ),
    ]
