# Generated by Django 5.2.6 on 2025-09-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="material_tooltip",
            field=models.TextField(
                default=None, help_text="Material type (e.g., Akzhal, Lead concentrate)"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DropdownOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name (e.g., material, delivery_term)",
                        max_length=100,
                    ),
                ),
                (
                    "option_key",
                    models.CharField(
                        help_text="Option key (e.g., akzhal, dap)", max_length=100
                    ),
                ),
                (
                    "option_value",
                    models.CharField(
                        help_text="Display value (e.g., Akzhal, DAP (Delivered at Place))",
                        max_length=255,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Order for display"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this option is active"
                    ),
                ),
                (
                    "tooltip_text",
                    models.TextField(
                        blank=True, help_text="Tooltip content for info icon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dropdown Option",
                "verbose_name_plural": "Dropdown Options",
                "ordering": ["field_name", "display_order", "option_key"],
                "unique_together": {("field_name", "option_key")},
            },
        ),
    ]
