# Generated by Django 5.2.6 on 2025-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_alter_deal_options_deal_created_at_deal_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dropdownoption",
            options={
                "ordering": ["field_name", "display_order", "option_value"],
                "verbose_name": "Dropdown Option",
                "verbose_name_plural": "Dropdown Options",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dropdownoption",
            unique_together={("field_name", "option_value")},
        ),
        migrations.AlterField(
            model_name="dropdownoption",
            name="option_value",
            field=models.JSONField(
                help_text='Display value (e.g., {"akzhal": "Akzhal", "dap": "DAP (Delivered at Place)"})'
            ),
        ),
        migrations.RemoveField(
            model_name="dropdownoption",
            name="option_key",
        ),
    ]
