# Generated by Django 5.2.6 on 2025-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_alter_dropdownoption_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropdownoption",
            name="display_order",
            field=models.IntegerField(
                blank=True, default=0, help_text="Order for display", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dropdownoption",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether this option is active",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dropdownoption",
            name="option_value",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Display value (e.g., {"akzhal": "Akzhal", "dap": "DAP (Delivered at Place)"})',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dropdownoption",
            name="tooltip_text",
            field=models.TextField(
                blank=True, help_text="Tooltip content for info icon", null=True
            ),
        ),
    ]
