# Generated by Django 5.2.6 on 2025-09-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0005_alter_dropdownoption_display_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropdownoption",
            name="option_value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
