# Generated by Django 5.2.6 on 2025-09-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0007_alter_dropdownoption_option_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropdownoption",
            name="option_value",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Display value (e.g., {"akzhal": "Akzhal", "dap": "DAP (Delivered at Place)"})',
                null=True,
            ),
        ),
    ]
