# Generated by Django 5.2.6 on 2025-09-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0008_alter_dropdownoption_option_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dropdownoption",
            options={
                "ordering": ["field_name", "display_order", "option_values"],
                "verbose_name": "Dropdown Option",
                "verbose_name_plural": "Dropdown Options",
            },
        ),
        migrations.RenameField(
            model_name="dropdownoption",
            old_name="option_value",
            new_name="option_values",
        ),
        migrations.AlterUniqueTogether(
            name="dropdownoption",
            unique_together={("field_name", "option_values")},
        ),
    ]
