# Generated by Django 5.2.6 on 2025-09-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0009_alter_dropdownoption_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="material_tooltip",
        ),
    ]
