# Generated by Django 5.2.6 on 2025-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0010_remove_deal_material_tooltip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the deal was created",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the deal was last updated",
                null=True,
            ),
        ),
    ]
