# Generated by Django 5.2.6 on 2025-09-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0011_alter_deal_created_at_alter_deal_updated_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Deal",
            new_name="BusinessConfirmationDeal",
        ),
    ]
