# Generated by Django 5.2.6 on 2025-09-07 13:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0012_rename_deal_businessconfirmationdeal"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewBusinessConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seller",
                    models.CharField(
                        default="Open Mineral",
                        help_text="Seller company name",
                        max_length=255,
                    ),
                ),
                (
                    "buyer",
                    models.CharField(
                        default="Company A, John Materials",
                        help_text="Buyer company name",
                        max_length=255,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        help_text="Material type (e.g., Akzhal, Lead concentrate)",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity in specified unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the deal was created",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the deal was last updated",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="businessconfirmationdeal",
            options={},
        ),
        migrations.RemoveField(
            model_name="businessconfirmationdeal",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="businessconfirmationdeal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="businessconfirmationdeal",
            name="material",
        ),
        migrations.RemoveField(
            model_name="businessconfirmationdeal",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="businessconfirmationdeal",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="businessconfirmationdeal",
            name="status",
        ),
        migrations.RemoveField(
            model_name="businessconfirmationdeal",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="CommercialTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_term",
                    models.CharField(
                        help_text="Delivery term (e.g., DAP, FOB, CIF)", max_length=100
                    ),
                ),
                (
                    "delivery_point",
                    models.CharField(
                        blank=True, help_text="Delivery point location", max_length=255
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        blank=True,
                        help_text="Packaging type (e.g., Big Bags, Bulk)",
                        max_length=100,
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        help_text="Transport mode (e.g., Rail, Ship, Truck)",
                        max_length=100,
                    ),
                ),
                (
                    "inland_freight_buyer",
                    models.BooleanField(
                        default=False, help_text="Inland freight borne by buyer"
                    ),
                ),
                (
                    "shipment_start_date",
                    models.DateField(help_text="Shipment period start date"),
                ),
                (
                    "shipment_end_date",
                    models.DateField(help_text="Shipment period end date"),
                ),
                (
                    "evenly_distributed",
                    models.BooleanField(
                        default=True,
                        help_text="Shipments distributed evenly across period",
                    ),
                ),
                (
                    "treatment_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Treatment charge amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "treatment_charge_unit",
                    models.CharField(
                        default="dmt", help_text="Treatment charge unit", max_length=10
                    ),
                ),
                (
                    "refining_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Refining charge amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "refining_charge_unit",
                    models.CharField(
                        default="toz", help_text="Refining charge unit", max_length=10
                    ),
                ),
                (
                    "assay_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded assay file",
                        null=True,
                        upload_to="assay_files/%Y/%m/%d/",
                    ),
                ),
                (
                    "china_import_compliant",
                    models.BooleanField(
                        default=True,
                        help_text="Material complies with China import standards",
                    ),
                ),
                (
                    "clauses",
                    models.JSONField(
                        default=list, help_text="List of additional clause strings"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the commercial terms were created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the commercial terms were last updated",
                    ),
                ),
                (
                    "business_confirmation_deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercial_terms",
                        to="deals.businessconfirmationdeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Terms",
                "verbose_name_plural": "Commercial Terms",
            },
        ),
    ]
