# Generated by Django 5.2.6 on 2025-09-07 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0013_newbusinessconfirmation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessconfirmationdeal",
            options={
                "verbose_name": "Business Confirmation Deal",
                "verbose_name_plural": "Business Confirmation Deals",
            },
        ),
        migrations.RemoveField(
            model_name="commercialterms",
            name="business_confirmation_deal",
        ),
        migrations.RemoveField(
            model_name="newbusinessconfirmation",
            name="status",
        ),
        migrations.AddField(
            model_name="businessconfirmationdeal",
            name="commercial_terms",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_confirmation_deal",
                to="deals.commercialterms",
            ),
        ),
        migrations.AddField(
            model_name="businessconfirmationdeal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date and time when the business confirmation deal was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessconfirmationdeal",
            name="new_business_confirmation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_confirmation_deal",
                to="deals.newbusinessconfirmation",
            ),
        ),
        migrations.AddField(
            model_name="businessconfirmationdeal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="businessconfirmationdeal",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the business confirmation deal was last updated",
            ),
        ),
        migrations.AddField(
            model_name="businessconfirmationdeal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_confirmation_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newbusinessconfirmation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
