# Generated by Django 5.2.6 on 2025-09-07 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0014_alter_businessconfirmationdeal_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause",
                    models.TextField(
                        blank=True, help_text="Additional clause", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the additional clause was created",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the additional clause was last updated",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Clause",
                "verbose_name_plural": "Additional Clauses",
            },
        ),
        migrations.RemoveField(
            model_name="commercialterms",
            name="evenly_distributed",
        ),
        migrations.AddField(
            model_name="commercialterms",
            name="shipment_evenly_distributed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Shipments distributed evenly across period",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="china_import_compliant",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Material complies with China import standards",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="clauses",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of additional clause strings",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the commercial terms were created",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="delivery_point",
            field=models.CharField(
                blank=True,
                help_text="Delivery point location",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="delivery_term",
            field=models.CharField(
                blank=True,
                help_text="Delivery term (e.g., DAP, FOB, CIF)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="inland_freight_buyer",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Inland freight borne by buyer",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="packaging",
            field=models.CharField(
                blank=True,
                help_text="Packaging type (e.g., Big Bags, Bulk)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="refining_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Refining charge amount",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="refining_charge_unit",
            field=models.CharField(
                blank=True,
                default="toz",
                help_text="Refining charge unit",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="shipment_end_date",
            field=models.DateField(
                blank=True, help_text="Shipment period end date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="shipment_start_date",
            field=models.DateField(
                blank=True, help_text="Shipment period start date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="transport_mode",
            field=models.CharField(
                blank=True,
                help_text="Transport mode (e.g., Rail, Ship, Truck)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="treatment_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Treatment charge amount",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="treatment_charge_unit",
            field=models.CharField(
                blank=True,
                default="dmt",
                help_text="Treatment charge unit",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commercialterms",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the commercial terms were last updated",
                null=True,
            ),
        ),
    ]
