# Generated by Django 5.2.6 on 2025-09-07 17:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0015_additionalclause_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prepayment_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prepayment percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "prepayment_trigger",
                    models.CharField(
                        blank=True,
                        help_text="Prepayment trigger event",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "provisional_payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="Provisional payment terms description",
                        null=True,
                    ),
                ),
                (
                    "final_payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="Final payment terms description",
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method (e.g., T/T, L/C)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="USD",
                        help_text="Payment currency",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "triggering_event",
                    models.CharField(
                        blank=True,
                        help_text="General triggering event",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reference_document",
                    models.CharField(
                        blank=True,
                        help_text="Reference document type",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "final_determination_location",
                    models.CharField(
                        blank=True,
                        help_text="Final determination location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "buyer_cost_share_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Buyer cost share percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "seller_cost_share_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Seller cost share percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "nominated_by",
                    models.CharField(
                        blank=True,
                        help_text="Surveyor nominated by",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "agreed_by",
                    models.CharField(
                        blank=True,
                        help_text="Surveyor agreed by",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "surveyor_notes",
                    models.TextField(blank=True, help_text="Additional surveyor notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the payment terms were created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the payment terms were last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Terms",
                "verbose_name_plural": "Payment Terms",
            },
        ),
        migrations.AddField(
            model_name="businessconfirmationdeal",
            name="payment_terms",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_confirmation_deal",
                to="deals.paymentterms",
            ),
        ),
    ]
