# Generated by Django 5.2.6 on 2025-09-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0016_paymentterms_businessconfirmationdeal_payment_terms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newbusinessconfirmation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "New Business Confirmation",
                "verbose_name_plural": "New Business Confirmations",
            },
        ),
    ]
