# Generated by Django 5.2.6 on 2025-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0017_alter_newbusinessconfirmation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalclause",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Additional Clause",
                "verbose_name_plural": "Additional Clauses",
            },
        ),
        migrations.AddField(
            model_name="additionalclause",
            name="display_order",
            field=models.IntegerField(
                blank=True, default=0, help_text="Order for display", null=True
            ),
        ),
    ]
